#!/usr/bin/env bash
# Build UNS images and pull third-party images on the cloud EC2 host.
set -euo pipefail
# shellcheck source=common.sh
. "$(cd "$(dirname "$0")" && pwd)/common.sh"

REPO_ROOT="${UNS_REPO_ROOT:?}"
BUNDLE_DIR="${UNS_CLOUD_BUNDLE:-${REPO_ROOT}/deploy/cloud}"
TAG="${UNS_IMAGE_TAG:-aws-demo}"
HIVEMQ_BROKER_IMAGE="${UNS_HIVEMQ_BROKER_IMAGE:?Set UNS_HIVEMQ_BROKER_IMAGE to a licensed HiveMQ broker image}"

cd "${REPO_ROOT}"
GIT_HASH="$(git rev-parse --short HEAD 2>/dev/null || echo aws-demo)"

build() {
  local dockerfile="$1"
  local name="$2"
  log "Building ${name}:${TAG} from ${dockerfile}"
  docker build \
    --build-arg "GIT_HASH=${GIT_HASH}" \
    -t "${name}:${TAG}" \
    -f "${dockerfile}" \
    .
}

build deploy/cloud/proxy/Dockerfile uns-cloud-proxy
build 11_frontend/Dockerfile uns-frontend
build 07_uns_graphql/Dockerfile uns-graphql
build 09_uns_model/Dockerfile uns-model
build 06_uns_kafka/Dockerfile uns-kafka-mapper
build 04_uns_historian/Dockerfile uns-historian
build 03_uns_graphdb/Dockerfile uns-graphdb
build 14_uns_datalake/Dockerfile uns-datalake
build 12_uns_oee/Dockerfile uns-oee

log "Pulling third-party images"
docker pull postgres:16-alpine
docker pull timescale/timescaledb:pg16-2025.04.0
docker pull neo4j:5.26.0-community
docker pull apache/kafka:3.9.0
docker pull quay.io/keycloak/keycloak:26.0.7
docker pull grafana/grafana:11.5.2
docker pull prom/prometheus:v3.2.1
docker pull "${HIVEMQ_BROKER_IMAGE}"

if [[ -n "${UNS_HIVEMQ_LICENSE_FILE:-}" && -f "${UNS_HIVEMQ_LICENSE_FILE}" ]]; then
  ensure_dir "${BUNDLE_DIR}/broker/license" 0750
  cp "${UNS_HIVEMQ_LICENSE_FILE}" "${BUNDLE_DIR}/broker/license/license.lic"
  log "Copied HiveMQ license into ${BUNDLE_DIR}/broker/license"
fi

BROKER_VOLUMES=""
if [[ -f "${BUNDLE_DIR}/broker/license/license.lic" ]]; then
  BROKER_VOLUMES=$(cat <<'VOL'
    volumes:
      - broker-data:/opt/hivemq/data
      - broker-config:/opt/hivemq/conf
      - ./broker/config.xml:/opt/hivemq/conf/config.xml:ro
      - ./broker/authorization:/opt/hivemq/conf/authorization:ro
      - ./secrets/broker-tls:/opt/hivemq/conf/tls:ro
      - ./broker/license/license.lic:/opt/hivemq/license/license.lic:ro
VOL
)
fi

cat > "${BUNDLE_DIR}/compose.images.yml" <<EOF
# Generated by cloud-build-images.sh. Not a production digest-pinned release.
services:
  uns_proxy:
    image: uns-cloud-proxy:${TAG}
  uns_mqtt_broker:
    image: ${HIVEMQ_BROKER_IMAGE}
${BROKER_VOLUMES}
  uns_timescale_db:
    image: timescale/timescaledb:pg16-2025.04.0
  uns_neo4j_db:
    image: neo4j:5.26.0-community
  uns_kafka_broker:
    image: apache/kafka:3.9.0
  kafka_topic_init:
    image: uns-kafka-mapper:${TAG}
  tsdb_setup_script:
    image: postgres:16-alpine
  asset_model_setup:
    image: uns-model:${TAG}
  graphdb_client:
    image: uns-graphdb:${TAG}
  historian_client:
    image: uns-historian:${TAG}
  kafka_mapper_client:
    image: uns-kafka-mapper:${TAG}
  datalake_mapper:
    image: uns-datalake:${TAG}
  oee_client:
    image: uns-oee:${TAG}
  graphql_server:
    image: uns-graphql:${TAG}
  route_release_worker:
    image: uns-graphql:${TAG}
  publication_outbox_worker:
    image: uns-graphql:${TAG}
  uns_keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
  uns_frontend:
    image: uns-frontend:${TAG}
  uns_grafana:
    image: grafana/grafana:11.5.2
  uns_prometheus:
    image: prom/prometheus:v3.2.1
EOF

log "Wrote ${BUNDLE_DIR}/compose.images.yml"
log "Image build complete"
