#!/usr/bin/env bash
# Build edge-agent and optional simulator images; write compose.images.yml.
set -euo pipefail
# shellcheck source=common.sh
. "$(cd "$(dirname "$0")" && pwd)/common.sh"

REPO_ROOT="${UNS_REPO_ROOT:?}"
DESTINATION="${UNS_EDGE_DESTINATION:-/opt/uns-edge}"
TAG="${UNS_IMAGE_TAG:-aws-demo}"
HIVEMQ_EDGE_IMAGE="${UNS_HIVEMQ_EDGE_IMAGE:?Set UNS_HIVEMQ_EDGE_IMAGE to a HiveMQ Edge image}"
ENABLE_SIM="${UNS_EDGE_ENABLE_SIM:-1}"

cd "${REPO_ROOT}"
GIT_HASH="$(git rev-parse --short HEAD 2>/dev/null || echo aws-demo)"

log "Building uns-edge-agent:${TAG}"
docker build --build-arg "GIT_HASH=${GIT_HASH}" -t "uns-edge-agent:${TAG}" -f 15_uns_edge_agent/Dockerfile .

log "Pulling ${HIVEMQ_EDGE_IMAGE}"
docker pull "${HIVEMQ_EDGE_IMAGE}"

SIM_SERVICES=""
if [[ "${ENABLE_SIM}" == "1" ]]; then
  log "Building edge-sim images"
  docker build -t "uns-oee-simulator:${TAG}" -f conf/simulator/Dockerfile .
  docker build -t "uns-multi-system-simulator:${TAG}" -f conf/simulator/Dockerfile.multi-system .
  docker build -t "uns-opcua-simulator:${TAG}" -f conf/simulator/protocols/Dockerfile.opcua .
  docker build -t "uns-modbus-simulator:${TAG}" -f conf/simulator/protocols/Dockerfile.modbus .
  SIM_SERVICES=$(cat <<EOF
  oee-simulator:
    image: uns-oee-simulator:${TAG}
    secrets:
      - mqtt_sim_credentials
      - mqtt_sim_tls
      - mqtt_ca
      - mqtt_cert
      - mqtt_key
  multi-system-simulator:
    image: uns-multi-system-simulator:${TAG}
    secrets:
      - mqtt_sim_credentials
      - mqtt_sim_tls
      - mqtt_ca
      - mqtt_cert
      - mqtt_key
  opcua-simulator:
    image: uns-opcua-simulator:${TAG}
  modbus-simulator:
    image: uns-modbus-simulator:${TAG}
secrets:
  mqtt_ca:
    file: ./simulation/secrets/edge-mqtt-ca.pem
  mqtt_cert:
    file: ./simulation/secrets/edge-mqtt-client.pem
  mqtt_key:
    file: ./simulation/secrets/edge-mqtt-client.key
EOF
)
fi

cat > "${DESTINATION}/compose.images.yml" <<EOF
# Generated by edge-build-images.sh. Not a production digest-pinned release.
services:
  hivemq-edge:
    image: ${HIVEMQ_EDGE_IMAGE}
    volumes:
      - ./hivemq:/opt/hivemq/conf
      - edge-data:/opt/hivemq/data
      - edge-bridge:/opt/hivemq/bridge-buffer
  uns-edge-agent:
    image: uns-edge-agent:${TAG}
    volumes:
      - agent-data:/var/lib/uns-edge-agent
      - ./secrets/cloud-ca.pem:/etc/uns/cloud-ca.pem:ro
${SIM_SERVICES}
EOF

log "Wrote ${DESTINATION}/compose.images.yml"
