global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: uns_historian
    static_configs:
      - targets: ["historian_client:9091"]

  - job_name: uns_graphdb
    static_configs:
      - targets: ["graphdb_client:9092"]

  - job_name: uns_opcua
    static_configs:
      - targets: ["opcua_client:9093"]

  - job_name: uns_simulator
    static_configs:
      - targets: ["uns_simulator:9093"]
