default:
  mqtt:
    username: "#<enter the username for the mqtt broker>"
    password: "#<enter the password for the mqtt broker>"
    tls:
      #ca_certs:
      #certfile:
      #keyfile:
      #cert_reqs:
      #ciphers:
      #keyfile_password:
      #insecure_cert: true

  graphdb:
    username: "#<enter the username for the graph database>"
    password: "#<enter the password for the graph database>"

  historian:
    username: "#<enter the username for the Timescale database>"
    password: "#<enter the password for the Timescale database>"
    sslmode:
    sslcert:
    sslkey:
    sslrootcert:
    sslcrl:

  kafka:
    config:
      security.protocol: "SASL_SSL"
      sasl.mechanisms: "SCRAM-SHA-256"
      sasl.username: ""
      sasl.password: ""
      ssl.cipher.suites: ""
      ssl.curves.list: ""
      ssl.sigalgs.list: ""
      ssl.key.location: ""
      ssl.key.password: ""
      ssl.key.pem: ""

dynaconf_merge: true
